/**
 * scripts/build-image-prompt-sheet.ts
 *
 * Emits a single paste-ready Markdown sheet of every AI-image prompt in the
 * exercise library, so the images can be generated by hand (ChatGPT app,
 * Midjourney, etc.) when the API route is not being used.
 *
 *   npx tsx scripts/build-image-prompt-sheet.ts > docs/exercise-image-prompt-sheet.md
 *
 * Two families:
 *   - Exercise ILLUSTRATIONS  lib/exercise-image-prompts.ts
 *   - Self-check test PHOTOS   lib/self-test-image-prompts.ts
 *
 * Filename convention: save each generated image as `<id>.png`. The branded
 * PhysioOnClick footer is composited on later (scripts/brand-exercise-images.ts)
 * -- never ask the generator for the logo.
 */
import {
  exerciseImagePrompts,
  fullImagePrompt,
} from "@/lib/exercise-image-prompts";
import {
  selfTestImagePrompts,
  fullSelfTestImagePrompt,
} from "@/lib/self-test-image-prompts";
import { exercises } from "@/lib/exercises";
import { selfTests } from "@/lib/self-tests";

const exById = new Map(exercises.map((e) => [e.id, e]));

const AREA_LABEL: Record<string, string> = {
  lower_limb: "Lower limb (knee / hip / ankle / calf)",
  upper_limb: "Upper limb (shoulder / elbow / wrist)",
  spine: "Spine (lower back / neck / mid-back)",
  balance_walking: "Balance & walking",
  neuro: "Neurological rehab (incl. facial)",
  post_op: "After surgery",
  pelvic_health: "Pregnancy & pelvic health",
  paediatric: "Children's physiotherapy",
  general: "General fitness & pain management",
};

const areaOrder = [
  "spine",
  "upper_limb",
  "lower_limb",
  "balance_walking",
  "post_op",
  "pelvic_health",
  "neuro",
  "paediatric",
  "general",
];

const idNum = (id: string): number => {
  const m = /^ex-(\d+)$/.exec(id);
  return m ? Number(m[1]) : Number.MAX_SAFE_INTEGER;
};

const out: string[] = [];
const p = (s = "") => out.push(s);

const exCount = Object.keys(exerciseImagePrompts).length;
const stCount = Object.keys(selfTestImagePrompts).length;

p("# PhysioOnClick -- exercise & self-check image prompt sheet");
p("");
p(`_Generated ${new Date().toISOString().slice(0, 10)}. ${exCount} exercise illustrations + ${stCount} self-check test photos._`);
p("");
p("## How to use this");
p("");
p("- Generate one image per entry. **Save it as `<id>.png`** -- the id is the bold code at the start of each entry (e.g. `ex-55.png`, `test-full-can-3.png`). The filename is how the site matches the image to the exercise, so it must be exact.");
p("- Square output, roughly **1024 x 1024**, on a plain pale background.");
p("- **Do not ask for any logo, wordmark or caption.** The PhysioOnClick footer band is added afterwards by a separate step.");
p("- Two different looks, kept separate below: the **exercise illustrations** are a clean anatomical-textbook drawing; the **self-check test photos** are realistic photographs of one consistent model.");
p("- Try to keep the **same figure, clothing and background across a whole section** so a page of thumbnails reads as one set.");
p("- Hand the finished PNGs back in one folder. They are reviewed by the physiotherapist, then uploaded. Until an image is uploaded the site shows a placeholder -- nothing breaks if some are missing.");
p("");
p("---");
p("");
p("# Part 1 -- Exercise illustrations");
p("");
p("_Style: detailed medical illustration, single clothed figure, realistic proportions and joint angles, the working muscles lightly shaded, one sky-blue (#0EA5E9) movement arrow, navy (#043246) outlines, no text._");
p("");

const byArea: Record<string, string[]> = {};
for (const id of Object.keys(exerciseImagePrompts)) {
  const area = exById.get(id)?.clinicalArea ?? "general";
  (byArea[area] ||= []).push(id);
}

for (const area of areaOrder) {
  const ids = (byArea[area] ?? []).sort(
    (a, b) => idNum(a) - idNum(b) || a.localeCompare(b),
  );
  if (!ids.length) continue;
  p(`## ${AREA_LABEL[area] ?? area} (${ids.length})`);
  p("");
  for (const id of ids) {
    const ex = exById.get(id);
    const isFace = id.startsWith("face-") || ex?.bodyPart === "Face";
    p(`### \`${id}\` -- ${ex?.title ?? id}`);
    p("");
    if (isFace) {
      p("_Face exercise: a head-and-shoulders close-up of the face making this expression, both sides shown for symmetry. **No movement arrow.** Ignore the arrow / three-quarter-view wording in the prompt below._");
      p("");
    }
    p("```");
    p(fullImagePrompt(id) ?? "(no prompt)");
    p("```");
    p("");
  }
}

p("---");
p("");
p("# Part 2 -- Self-check test photos");
p("");
p("_Style: realistic clean photograph, one consistent adult model in plain grey activewear on a plain pale studio background, natural even lighting, a single sky-blue (#0EA5E9) arrow only where movement direction matters, no text._");
p("");

for (const t of selfTests) {
  p(`## ${t.name} (${t.steps.length} steps)`);
  p("");
  p(`_Checks: ${t.assesses}. Keep the SAME model, clothing and background across all ${t.steps.length} steps._`);
  p("");
  t.steps.forEach((step, i) => {
    p(`### \`${step.imageId}\` -- step ${i + 1}: ${step.label}`);
    p("");
    p("```");
    p(fullSelfTestImagePrompt(step.imageId) ?? "(no prompt)");
    p("```");
    p("");
  });
}

p("---");
p("");
p("## Checklist for handing images back");
p("");
p(`- [ ] ${exCount} exercise illustrations, each named \`ex-N.png\` / \`face-*.png\``);
p(`- [ ] ${stCount} self-check test photos, each named \`test-*.png\``);
p("- [ ] All square, ~1024px, plain pale background, no text or logo");
p("- [ ] One folder, shared back");

process.stdout.write(out.join("\n") + "\n");
